version: '3'

services:
  truffle-ganache:
    container_name: truffle-ganache
    build: ./blockchain
    ports:
      - 7545:7545
    volumes:
      - ./blockchain:/app
    entrypoint:
      - yarn
      - ganache
      - --db=/app/ganache_data
      - --networkId
      - '5777'
      - --hostname
      - '0.0.0.0'
      - --port
      - '7545'
      - --mnemonic
      - grape solution air laundry garage body erupt thought ritual renew ginger tackle

  middleware:
    container_name: middleware
    build: ./middleware
    ports:
      - 8000:8000
    volumes: 
      - ./middleware:/usr/src/app
    entrypoint: 
      - "uvicorn"
      - "src.main:app"
      - "--host"
      - "0.0.0.0"
      - "--port"
      - "8000"
      - "--reload"
    depends_on:
      - truffle-ganache    
